openAI:
  api_key: YOUR_OPENAI_API_KEY
  engine: text-davinci-003
  max_tokens: 50
  temperature: 0.7
elevenLabs:
  api_key: YOUR_ELEVENLABS_API_KEY
  voice: Adam
  model: eleven_monolingual_v1
log_level: INFO
